name: dragon flow
on: push
jobs: 
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name : checkout repo
      uses: actions/checkout@v4 

    - name: List Repo Files
      run: ls -ltra


    - name : Execute Shell Script
      uses: ./ascii.sh

   