name: dragon flow
on: push
jobs: 
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name : checkout repo
      uses: actions/checkout@v4 

    - name: List Repo Files
      run: ls -ltra


    - name: Change permissions
      run: chmod +x ./ascii.sh

    - name: Execute Shell Script
      run: ./ascii.sh



   